// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// 
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkXB6x0KveH4abPpADviZ08IFa8DvYnXY',
    appId: '1:112067599353:web:40ec58c7689e9ccb5afb28',
    messagingSenderId: '112067599353',
    projectId: 'bandw-questions',
    authDomain: 'bandw-questions.firebaseapp.com',
    databaseURL: 'https://bandw-questions-default-rtdb.firebaseio.com',
    storageBucket: 'bandw-questions.firebasestorage.app',
    measurementId: 'G-T3SF3CNE5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbFG-RsIPr1-sV4Xvi67gb470Evr2gWOo',
    appId: '1:112067599353:android:f17696e50c115ed05afb28',
    messagingSenderId: '112067599353',
    projectId: 'bandw-questions',
    databaseURL: 'https://bandw-questions-default-rtdb.firebaseio.com',
    storageBucket: 'bandw-questions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm3jPEmUVgJ8baV3G9nXwNwXT-EmY1lPI',
    appId: '1:112067599353:ios:2921c13e387583be5afb28',
    messagingSenderId: '112067599353',
    projectId: 'bandw-questions',
    databaseURL: 'https://bandw-questions-default-rtdb.firebaseio.com',
    storageBucket: 'bandw-questions.firebasestorage.app',
    iosBundleId: 'com.example.mvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm3jPEmUVgJ8baV3G9nXwNwXT-EmY1lPI',
    appId: '1:112067599353:ios:2921c13e387583be5afb28',
    messagingSenderId: '112067599353',
    projectId: 'bandw-questions',
    databaseURL: 'https://bandw-questions-default-rtdb.firebaseio.com',
    storageBucket: 'bandw-questions.firebasestorage.app',
    iosBundleId: 'com.example.mvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkXB6x0KveH4abPpADviZ08IFa8DvYnXY',
    appId: '1:112067599353:web:184fc1573afa33f45afb28',
    messagingSenderId: '112067599353',
    projectId: 'bandw-questions',
    authDomain: 'bandw-questions.firebaseapp.com',
    databaseURL: 'https://bandw-questions-default-rtdb.firebaseio.com',
    storageBucket: 'bandw-questions.firebasestorage.app',
    measurementId: 'G-0D4WDTKH9Y',
  );
}
